### ISSUE TITLE
mypy support

### ISSUE THREAD

**Issue by sobolevn** [rsinger86/drf-typed-views#6]
Hi! Thanks for the awesome project.

I would like to ask if you consider adding `mypy` check ensuring that type annotations in both your and user projects are correct.

There are already stubs for django and drf available here:
- https://github.com/typeddjango/django-stubs
- https://github.com/typeddjango/djangorestframework-stubs

It would be an awesome addition.

**Comment by rsinger86** [comment]
Thanks for the suggestion. I'm not very familiar with stubs. How might a "mypy check" be integrated?

**Comment by sobolevn** [comment]
It is defined by [PEP 561](https://mypy.readthedocs.io/en/latest/installed_packages.html)

I hope this helps!
